### ISSUE TITLE
Use pre-built docker images

### ISSUE THREAD

**Issue by fjebaker** [aimlac-7564616D/composer#11]
Both for the smoke tests and deployment, the entire system is slowed (to like 30+ minutes) by having to build the model and web-view images.

I know @dingsheng-ong has since uploaded images to docker hub, but these need to be linked into the docker-compose file.

**Comment by dingsheng-ong** [comment]
> Both for the smoke tests and deployment, the entire system is slowed (to like 30+ minutes) by having to build the model and web-view images.
> 
> I know @dingsheng-ong has since uploaded images to docker hub, but these need to be linked into the docker-compose file.

Yup, I'm now working on slimming down the pre-build image for `models`. Once it's done, I'll update the `Dockerfile`.

**Comment by fjebaker** [comment]
@dingsheng-ong Added
- https://github.com/aimlac-7564616D/models/pull/7
- https://github.com/aimlac-7564616D/web-view/pull/8

to automatically build the latest docker images on push to main; the images end up [on docker hub here](https://hub.docker.com/u/dustpancake).

**Comment by fjebaker** [comment]
This is now completed with the fully updated docker-compose file in 
- #17
